### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Smartnir)
add_subdirectory(SmartnirContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Smartnir_workingplugin
    SmartnirContentplugin
    QtQuickDesignerComponents)